FROM dockerhub.test.wacai.info/xianglong/shield-cache:1.0

RUN apt-get update && apt-get install -y chromium

ENV TZ=Asia/Jakarta
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
